### Basic Torch

In [2]:
import torch 

In [ ]:

x = torch.tensor([[1, 4, 2], [2, 5, 8]], dtype=torch.float32, device='cuda')

print(x)
print(x.dtype)
print(x.device)         ## Checks on which device the torch is
print(x.dtype)

- Other methods to init tensors

In [ ]:
x = torch.empty(size=(3,3))
print(x)                    ## Gives the output as the whatever value is present at the memory not necessaryly zero
x = torch.zeros(3,3)        ## This gives us the matrix with values zeros
print(x)

x = torch.rand(size=(3,3))  ## Gives random values for the size 3x3, where prob of each value is equal
print(x)

x = torch.randn(3,3)        ## Gives random values with varience = 0 and std = 1, means values close to normal 0 will have more chance of appearing
print(x)

x = torch.eye(3)        ## Gives identiy matrix with the number of rows and columns mentioned 
print(x)

x = torch.ones(5,5)         ## Gives the complete matrix with 1`s
print(x)

x = torch.arange(1,10,2)      ## Gives the values from 0 to 9 in the intervals of 2 each 
print(x)

x = torch.linspace(1, 20, 5, dtype=int)     ## This gives us equal intevals of 5 between 1 to 20 
print(x)

x = torch.empty(5,5).uniform_(0,1)      ## This gives the power to set lower and upper bound of the matrix
print(x)

x = torch.diag(torch.arange(3,6))       ## Gives us the diagonal with values from arange
print(x)

- Convert tensors into other dtypes

In [ ]:
x = torch.arange(4)
print(x.bool())      ## Only the 0 value will be False rest all be True
print(x.short())        ## converts to int16
print(x.long())         ## converts to int64
print(x.half())         ## converts to float 16 as half of float32
print(x.double())           ## converts to float64 from float32

- Array to tensor and vice versa

In [101]:
import numpy as np
x = np.arange(5)
y = torch.from_numpy(x)        ## Converts the array to tensor from numpy
print(x)
print(y)
y = y.numpy()           ## Convert back to numpy from tensor 
print(y)

[0 1 2 3 4]
tensor([0, 1, 2, 3, 4])
[0 1 2 3 4]


- Maths operation 

In [61]:
x = torch.tensor([3,4,5])
y = torch.tensor([5,6,7])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

print('-' * 25)
## Inplace 
t = 4
t+=x
print(t)  ## Doesnt create any new copy 
print(t.add_(x)) ## any function followed by (_) will have an inplace effect on the variable 

print('-' * 25)

## Exponential
print(x.pow(2))
## x ** 2 Does the same thing but without calling the pow() 

print('-' * 25)

## Matrix Multiplication       (Needs inner dim same)
a = torch.rand(2,3)
b = torch.rand(3,4)
print(torch.mm(a,b))        ## The shape of the matrix will be 2,4
## torch.matmul(a,b)        ## Does the same thing
## a @ b                    ## Does the same thing 

print('-' * 25)

## Matrix Power
a = torch.arange(1,5).reshape(2,2)

print(a)
print(a.matrix_power(2))        ## This is multiplying the matrix by itself 
print(a.pow(2))                 ## This is the power of elements    

print('-' * 25)

## Dot product --- Element wise multiplication followed by summation 

print(torch.dot(x,y))       ## Needs 1D vector that too of the same size to output a scalar      

print('-' * 25)

## Batch multiplication 

n = 1
m = 2
p = 4
batch = 32

a = torch.rand(batch, n, m)     ## Here mxm matches the shape for matrix multiplication
b = torch.rand(batch,m,p)

print(torch.bmm(a,b))          ## Gives the output in the shape of (batch, n, p)

print('-' * 25)


## Broadcasting Example  --> Allows operations by converting dimenstions btween vector and scalar
## Matching higher dimensions and shapes (make sure one dim is same)

## Pytorch always aligns the dimensitions from the right to the left 

x = torch.rand((3,3))
y = torch.rand(1,3)
print(x+y)
print(x-y)

print('-' * 25)

## Argmax returns the index 
## values, index = torch.max(x,dim=0)       ## returns both value and the index 

print(x)
print(torch.argmax(x))
values, index = torch.max(x, dim=0)     ## here dim=0 will squish the 0 (row) dimension so the output will be max of columns to make a single row 
values
# print(index)                                   ## same for the dim=1 will distory columns to make single columns so the max will be among rows

print('-' * 25)

## Equals
x = torch.tensor([2,3,4])
y = torch.tensor([2,5,4])

print(torch.eq(x,y))        ## This gives the true false for the values if they are equal

tensor([ 8, 10, 12])
tensor([-2, -2, -2])
tensor([15, 24, 35])
tensor([0.6000, 0.6667, 0.7143])
-------------------------
tensor([7, 8, 9])
tensor([10, 12, 14])
-------------------------
tensor([ 9, 16, 25])
-------------------------
tensor([[0.5095, 0.4498, 0.5969, 0.2538],
        [0.7804, 0.6862, 0.8856, 0.3867]])
-------------------------
tensor([[1, 2],
        [3, 4]])
tensor([[ 7, 10],
        [15, 22]])
tensor([[ 1,  4],
        [ 9, 16]])
-------------------------
tensor(74)
-------------------------
tensor([[[0.1768, 0.2308, 0.1938, 0.0822]],

        [[0.6098, 0.8479, 0.5650, 1.0362]],

        [[0.0076, 0.1015, 0.0417, 0.0895]],

        [[0.6004, 0.8150, 0.9774, 0.3736]],

        [[0.8798, 0.5336, 0.4746, 0.4574]],

        [[0.3011, 0.7317, 0.4870, 0.6330]],

        [[0.2762, 0.8116, 0.1489, 0.4534]],

        [[1.3742, 0.1884, 1.1869, 0.7173]],

        [[0.0930, 0.0472, 0.2531, 0.4686]],

        [[0.7270, 0.7499, 0.3824, 0.2708]],

        [[0.3998, 0.6482, 0.6154, 0