### Basic Torch

In [2]:
import torch 

In [ ]:

x = torch.tensor([[1, 4, 2], [2, 5, 8]], dtype=torch.float32, device='cuda')

print(x)
print(x.dtype)
print(x.device)         ## Checks on which device the torch is
print(x.dtype)

- Other methods to init tensors

In [ ]:
x = torch.empty(size=(3,3))
print(x)                    ## Gives the output as the whatever value is present at the memory not necessaryly zero
x = torch.zeros(3,3)        ## This gives us the matrix with values zeros
print(x)

x = torch.rand(size=(3,3))  ## Gives random values for the size 3x3, where prob of each value is equal
print(x)

x = torch.randn(3,3)        ## Gives random values with varience = 0 and std = 1, means values close to normal 0 will have more chance of appearing
print(x)

x = torch.eye(3)        ## Gives identiy matrix with the number of rows and columns mentioned 
print(x)

x = torch.ones(5,5)         ## Gives the complete matrix with 1`s
print(x)

x = torch.arange(1,10,2)      ## Gives the values from 0 to 9 in the intervals of 2 each 
print(x)

x = torch.linspace(1, 20, 5, dtype=int)     ## This gives us equal intevals of 5 between 1 to 20 
print(x)

x = torch.empty(5,5).uniform_(0,1)      ## This gives the power to set lower and upper bound of the matrix
print(x)

x = torch.diag(torch.arange(3,6))       ## Gives us the diagonal with values from arange
print(x)

- Convert tensors into other dtypes

In [ ]:
x = torch.arange(4)
print(x.bool())      ## Only the 0 value will be False rest all be True
print(x.short())        ## converts to int16
print(x.long())         ## converts to int64
print(x.half())         ## converts to float 16 as half of float32
print(x.double())           ## converts to float64 from float32

- Array to tensor and vice versa

In [101]:
import numpy as np
x = np.arange(5)
y = torch.from_numpy(x)        ## Converts the array to tensor from numpy
print(x)
print(y)
y = y.numpy()           ## Convert back to numpy from tensor 
print(y)

[0 1 2 3 4]
tensor([0, 1, 2, 3, 4])
[0 1 2 3 4]


- Maths operation 

In [ ]:
x = torch.tensor([3,4,5])
y = torch.tensor([5,6,7])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

## Inplace 
t = 4
t+=x
print(t)  ## Doesnt create any new copy 
print(t.add_(x)) ## any function followed by (_) will have an inplace effect on the variable 

## Exponential
print(x.pow(2))
## x ** 2 Does the same thing but without calling the pow() 

tensor([ 8, 10, 12])
tensor([-2, -2, -2])
tensor([15, 24, 35])
tensor([0.6000, 0.6667, 0.7143])
tensor([7, 8, 9])
tensor([10, 12, 14])
tensor([ 9, 16, 25])
