### Basic Torch

In [1]:
import torch 

In [ ]:

x = torch.tensor([[1, 4, 2], [2, 5, 8]], dtype=torch.float32, device='cuda')

print(x)
print(x.dtype)
print(x.device)         ## Checks on which device the torch is
print(x.dtype)

- Other methods to init tensors

In [ ]:
x = torch.empty(size=(3,3))
print(x)                    ## Gives the output as the whatever value is present at the memory not necessaryly zero
x = torch.zeros(3,3)        ## This gives us the matrix with values zeros
print(x)

x = torch.rand(size=(3,3))  ## Gives random values for the size 3x3, where prob of each value is equal
print(x)

x = torch.randn(3,3)        ## Gives random values with varience = 0 and std = 1, means values close to normal 0 will have more chance of appearing
print(x)

x = torch.eye(3)        ## Gives identiy matrix with the number of rows and columns mentioned 
print(x)

x = torch.ones(5,5)         ## Gives the complete matrix with 1`s
print(x)

x = torch.arange(1,10,2)      ## Gives the values from 0 to 9 in the intervals of 2 each 
print(x)

x = torch.linspace(1, 20, 5, dtype=int)     ## This gives us equal intevals of 5 between 1 to 20 
print(x)

x = torch.empty(5,5).uniform_(0,1)      ## This gives the power to set lower and upper bound of the matrix
print(x)

x = torch.diag(torch.arange(3,6))       ## Gives us the diagonal with values from arange
print(x)

- Convert tensors into other dtypes

In [ ]:
x = torch.arange(4)
print(x.bool())      ## Only the 0 value will be False rest all be True
print(x.short())        ## converts to int16
print(x.long())         ## converts to int64
print(x.half())         ## converts to float 16 as half of float32
print(x.double())           ## converts to float64 from float32

- Array to tensor and vice versa

In [101]:
import numpy as np
x = np.arange(5)
y = torch.from_numpy(x)        ## Converts the array to tensor from numpy
print(x)
print(y)
y = y.numpy()           ## Convert back to numpy from tensor 
print(y)

[0 1 2 3 4]
tensor([0, 1, 2, 3, 4])
[0 1 2 3 4]


- Maths operation 

In [ ]:
x = torch.tensor([3,4,5])
y = torch.tensor([5,6,7])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

print('-' * 25)
## Inplace 
t = 4
t+=x
print(t)  ## Doesnt create any new copy 
print(t.add_(x)) ## any function followed by (_) will have an inplace effect on the variable 

print('-' * 25)

## Exponential
print(x.pow(2))
## x ** 2 Does the same thing but without calling the pow() 

print('-' * 25)

## Matrix Multiplication       (Needs inner dim same)
a = torch.rand(2,3)
b = torch.rand(3,4)
print(torch.mm(a,b))        ## The shape of the matrix will be 2,4
## torch.matmul(a,b)        ## Does the same thing
## a @ b                    ## Does the same thing 

print('-' * 25)

## Matrix Power
a = torch.arange(1,5).reshape(2,2)

print(a)
print(a.matrix_power(2))        ## This is multiplying the matrix by itself 
print(a.pow(2))                 ## This is the power of elements    

print('-' * 25)

## Dot product --- Element wise multiplication followed by summation 

print(torch.dot(x,y))       ## Needs 1D vector that too of the same size to output a scalar      

print('-' * 25)

## Batch multiplication 

n = 1
m = 2
p = 4
batch = 32

a = torch.rand(batch, n, m)     ## Here mxm matches the shape for matrix multiplication
b = torch.rand(batch,m,p)

print(torch.bmm(a,b))          ## Gives the output in the shape of (batch, n, p)

print('-' * 25)


## Broadcasting Example  --> Allows operations by converting dimenstions btween vector and scalar
## Matching higher dimensions and shapes (make sure one dim is same)

## Pytorch always aligns the dimensitions from the right to the left 

x = torch.rand((3,3))
y = torch.rand(1,3)
print(x+y)
print(x-y)

print('-' * 25)

## Argmax returns the index 
## values, index = torch.max(x,dim=0)       ## returns both value and the index 

print(x)
print(torch.argmax(x))
values, index = torch.max(x, dim=0)     ## here dim=0 will squish the 0 (row) dimension so the output will be max of columns to make a single row 
values
# print(index)                                   ## same for the dim=1 will distory columns to make single columns so the max will be among rows

print('-' * 25)

## Equals
x = torch.tensor([2,3,4])
y = torch.tensor([2,5,4])

print(torch.eq(x,y))        ## This gives the true false for the values if they are equal

torch.sort(y, descending=True)      ## sorts the tensor

In [ ]:
print(torch.clamp(x, min=4))  ## converts all the values less than 4 to 4 same can be done with max that will change all the values more then max to max

- Tensor indexing

In [85]:
x = torch.rand(5,4)
y = torch.arange(10)

print(x[0]) ## This gives the first row across all the columns 
## print(x[0,:])    ## GIves the same output --> i want oth row for all the columns 

print(x[:,0]) ## this gives all the rows for the first feature 

print(x[2,:])
print(x[2,0:2])         ## This gives the 2nd row for the columns starting from 0 to 1

index = [2,4,5]        ## This way we can create the index list that we want to get and then pass in the form on index to get mulitple index values 
print(y[index])

print('-'*30)
## Advance Indexing
x = torch.arange(10)
print(x[(x>2) & (x<7)])         ## We can perform other operations too while indexing 
print(x[x%2==0])                       ## Same thing just using the mod operator to fetch even numbers

print('-'*30)

## Other useful operations
torch.where(x>3, x, x+100)          ## This checks for values if they are greater than 3 its okay in not then they are added with 100

x = torch.tensor([2,12,2,32,3,4,23,32,423])
print(x.unique())          ## This gives us the unique values from our tensor
x.unsqueeze_(1)             ## This adds a dimention and makes it a column vector of shape(9,1)   --> using (_) makes it a inplace operation other wise we had to assign a variable to it first
print(x.ravel())           ## This makes the tensor into a flatterned tensor



tensor([0.1864, 0.0415, 0.1061, 0.6429])
tensor([0.1864, 0.4081, 0.7896, 0.2220, 0.0729])
tensor([0.7896, 0.1237, 0.1597, 0.0154])
tensor([0.7896, 0.1237])
tensor([2, 4, 5])
------------------------------
tensor([3, 4, 5, 6])
tensor([0, 2, 4, 6, 8])
------------------------------
tensor([  2,   3,   4,  12,  23,  32, 423])
tensor([  2,  12,   2,  32,   3,   4,  23,  32, 423])


- Reshaping Tensor