### Init Tensor

In [13]:
import torch 

In [ ]:

x = torch.tensor([[1, 4, 2], [2, 5, 8]], dtype=torch.float32, device='cuda')

print(x)
print(x.dtype)
print(x.device)         ## Checks on which device the torch is
print(x.dtype)

- Other methods to init tensors

In [ ]:
x = torch.empty(size=(3,3))
print(x)                    ## Gives the output as the whatever value is present at the memory not necessaryly zero
x = torch.zeros(3,3)        ## This gives us the matrix with values zeros
print(x)

x = torch.rand(size=(3,3))  ## Gives random values for the size 3x3, where prob of each value is equal
print(x)

x = torch.randn(3,3)        ## Gives random values with varience = 0 and std = 1, means values close to normal 0 will have more chance of appearing
print(x)

x = torch.eye(3)        ## Gives identiy matrix with the number of rows and columns mentioned 
print(x)

x = torch.ones(5,5)         ## Gives the complete matrix with 1`s
print(x)

x = torch.arange(1,10,2)      ## Gives the values from 0 to 9 in the intervals of 2 each 
print(x)

x = torch.linspace(1, 20, 5, dtype=int)     ## This gives us equal intevals of 5 between 1 to 20 
print(x)

tensor([[1.3532e-01, 0.0000e+00, 3.0402e+07],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.3593e-43, 0.0000e+00, 1.0482e-01]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.8987, 0.6595, 0.2149],
        [0.3893, 0.8078, 0.6863],
        [0.7726, 0.4869, 0.0794]])
tensor([[ 0.9223, -1.5613, -0.3064],
        [ 0.3991,  0.0813,  1.0700],
        [-1.7263, -0.1235,  2.8079]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([1, 3, 5, 7, 9])
tensor([ 1,  5, 10, 15, 20])
