### Basic Torch

In [2]:
import torch 

In [ ]:

x = torch.tensor([[1, 4, 2], [2, 5, 8]], dtype=torch.float32, device='cuda')

print(x)
print(x.dtype)
print(x.device)         ## Checks on which device the torch is
print(x.dtype)

- Other methods to init tensors

In [ ]:
x = torch.empty(size=(3,3))
print(x)                    ## Gives the output as the whatever value is present at the memory not necessaryly zero
x = torch.zeros(3,3)        ## This gives us the matrix with values zeros
print(x)

x = torch.rand(size=(3,3))  ## Gives random values for the size 3x3, where prob of each value is equal
print(x)

x = torch.randn(3,3)        ## Gives random values with varience = 0 and std = 1, means values close to normal 0 will have more chance of appearing
print(x)

x = torch.eye(3)        ## Gives identiy matrix with the number of rows and columns mentioned 
print(x)

x = torch.ones(5,5)         ## Gives the complete matrix with 1`s
print(x)

x = torch.arange(1,10,2)      ## Gives the values from 0 to 9 in the intervals of 2 each 
print(x)

x = torch.linspace(1, 20, 5, dtype=int)     ## This gives us equal intevals of 5 between 1 to 20 
print(x)

x = torch.empty(5,5).uniform_(0,1)      ## This gives the power to set lower and upper bound of the matrix
print(x)

x = torch.diag(torch.arange(3,6))       ## Gives us the diagonal with values from arange
print(x)

- Convert tensors into other dtypes

In [ ]:
x = torch.arange(4)
print(x.bool())      ## Only the 0 value will be False rest all be True
print(x.short())        ## converts to int16
print(x.long())         ## converts to int64
print(x.half())         ## converts to float 16 as half of float32
print(x.double())           ## converts to float64 from float32

- Array to tensor and vice versa

In [101]:
import numpy as np
x = np.arange(5)
y = torch.from_numpy(x)        ## Converts the array to tensor from numpy
print(x)
print(y)
y = y.numpy()           ## Convert back to numpy from tensor 
print(y)

[0 1 2 3 4]
tensor([0, 1, 2, 3, 4])
[0 1 2 3 4]


- Maths operation 

In [67]:
x = torch.tensor([3,4,5])
y = torch.tensor([5,6,7])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

print('-' * 25)
## Inplace 
t = 4
t+=x
print(t)  ## Doesnt create any new copy 
print(t.add_(x)) ## any function followed by (_) will have an inplace effect on the variable 

print('-' * 25)

## Exponential
print(x.pow(2))
## x ** 2 Does the same thing but without calling the pow() 

print('-' * 25)

## Matrix Multiplication       (Needs inner dim same)
a = torch.rand(2,3)
b = torch.rand(3,4)
print(torch.mm(a,b))        ## The shape of the matrix will be 2,4
## torch.matmul(a,b)        ## Does the same thing
## a @ b                    ## Does the same thing 

print('-' * 25)

## Matrix Power
a = torch.arange(1,5).reshape(2,2)

print(a)
print(a.matrix_power(2))        ## This is multiplying the matrix by itself 
print(a.pow(2))                 ## This is the power of elements    

print('-' * 25)

## Dot product --- Element wise multiplication followed by summation 

torch.dot(x,y)       ## Needs 1D vector that too of the same size to output a scalar      

print('-' * 25)

## Batch multiplication 

n = 1
m = 2
p = 4
batch = 32

a = torch.rand(batch, n, m)     ## Here mxm matches the shape for matrix multiplication
b = torch.rand(batch,m,p)

torch.bmm(a,b)          ## Gives the output in the shape of (batch, n, p)

tensor([ 8, 10, 12])
tensor([-2, -2, -2])
tensor([15, 24, 35])
tensor([0.6000, 0.6667, 0.7143])
-------------------------
tensor([7, 8, 9])
tensor([10, 12, 14])
-------------------------
tensor([ 9, 16, 25])
-------------------------
tensor([[0.8036, 1.2193, 1.3010, 0.7500],
        [1.2943, 1.7213, 1.7991, 1.1147]])
-------------------------
tensor([[1, 2],
        [3, 4]])
tensor([[ 7, 10],
        [15, 22]])
tensor([[ 1,  4],
        [ 9, 16]])
-------------------------
-------------------------


tensor([[[0.8867, 0.2943, 0.4887, 0.2762]],

        [[0.4899, 0.4692, 0.3330, 0.4834]],

        [[0.7183, 0.6391, 0.1045, 0.1829]],

        [[0.5289, 0.4733, 0.7056, 0.3523]],

        [[0.9402, 0.3768, 0.6345, 0.6036]],

        [[0.4341, 0.3772, 0.2255, 0.4126]],

        [[0.3641, 0.4040, 0.4525, 0.4044]],

        [[0.6064, 0.6530, 1.5069, 0.6521]],

        [[0.2226, 0.2938, 0.1880, 0.1780]],

        [[1.1742, 1.0525, 0.7519, 1.1968]],

        [[0.2601, 0.6266, 0.1550, 0.1849]],

        [[0.8218, 0.5361, 0.3762, 0.4002]],

        [[0.3150, 0.1411, 0.4813, 0.6886]],

        [[1.1078, 0.9960, 0.3308, 0.6565]],

        [[0.3595, 0.2809, 0.4051, 0.3964]],

        [[0.2028, 0.6677, 0.3818, 0.9836]],

        [[1.0696, 0.6233, 0.3911, 0.5667]],

        [[0.7334, 0.6886, 0.7613, 1.0006]],

        [[0.6964, 0.9963, 0.6653, 0.7590]],

        [[0.8969, 1.6095, 1.1004, 0.4409]],

        [[0.2616, 0.4296, 0.6851, 0.6646]],

        [[0.4981, 0.4939, 0.1266, 0.0573]],

        [[